title: thunderrrcunt GitHub Pages
author: thunderrrcunt
email: jen@thunderrrcunt.com
description: > # this means to ignore newlines until "baseurl:"
 My personal journey through GitHub, development and learning to code.

# social links
twitter_username: thunderrrcunt # DO NOT include the @ character, or else the build will fail!
github_username:  thunderrrcunt # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
